# -*- coding: utf-8 -*-
"""EDA_Covid_EC_ARG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tpNxw6F-FrdLlmqb7fEBxAmN-_Qbm5I
"""

import pandas as pd

# -------------------- Paso 1 — Exploración Manual de Datos (EDA) --------------------

# 1. Cargar el archivo
df = pd.read_csv("covid_EC_ARG.csv")

# 2. Perfilado básico

# Columnas y tipos
columnas_tipos = "--".join([f"{col} ({typ})" for col, typ in zip(df.columns, df.dtypes.astype(str))])

# Mínimo y máximo de new_cases
min_new_cases = df["new_cases"].min()
max_new_cases = df["new_cases"].max()

# Porcentaje de valores faltantes
pct_missing_new_cases = round(df["new_cases"].isna().mean() * 100, 2)
pct_missing_people_vaccinated = round(df["people_vaccinated"].isna().mean() * 100, 2) if "people_vaccinated" in df.columns else "N/A"

# Rango de fechas
fecha_min = pd.to_datetime(df["date"]).min()
fecha_max = pd.to_datetime(df["date"]).max()

# 3. Crear tabla de perfilado
tabla_perfilado = pd.DataFrame([{
    "min_new_cases": f"{min_new_cases:,.0f}",
    "max_new_cases": f"{max_new_cases:,.0f}",
    "pct_missing_new_cases": f"{pct_missing_new_cases:.2f}",
    "pct_missing_people_vaccinated": f"{pct_missing_people_vaccinated:.2f}" if pct_missing_people_vaccinated != "N/A" else "N/A",
    "fecha_min": fecha_min.strftime("%Y-%m-%d"),
    "fecha_max": fecha_max.strftime("%Y-%m-%d"),
    "columnas_tipos_datos": columnas_tipos
}])

# 4. Guardar tabla de perfilado
tabla_perfilado.to_csv("tabla_perfilado.csv", index=False)

print("tabla_perfilado.csv guardada correctamente.")